name: Tests
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'

jobs:
  build:
    name: Build
    runs-on: self-hosted
    timeout-minutes: 5
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go mod download

      - name: Build
        run: |
          go build -v .

  test:
    name: Acceptance Tests
    needs: build
    runs-on: self-hosted
    timeout-minutes: 15
    concurrency: test-acc
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go mod download

      - name: TF acceptance tests
        timeout-minutes: 10
        env:
          TF_ACC: "1"
          TF_ACC_TERRAFORM_VERSION: "1.0.8"

          TAIKUN_EMAIL: ${{ secrets.TAIKUN_EMAIL }}
          TAIKUN_PASSWORD: ${{ secrets.TAIKUN_PASSWORD }}

          PROMETHEUS_PASSWORD: ${{ secrets.PROMETHEUS_PASSWORD }}
          PROMETHEUS_URL: ${{ secrets.PROMETHEUS_URL }}
          PROMETHEUS_USERNAME: ${{ secrets.PROMETHEUS_USERNAME }}

        run: |
          go test -v -cover ./taikun